import { generateSmartResponse } from './src/sections/aiChatLogic.ts';

const testCases = [
  // === ANSWERABLE QUESTIONS (50 questions) ===
  
  // Skills variations
  { q: 'What skills does Karishma have?', expectType: 'skills', shouldDeferToEmail: false },
  { q: 'Can you do UI/UX design?', expectType: 'skills/services', shouldDeferToEmail: false },
  { q: 'What technologies do you know?', expectType: 'skills', shouldDeferToEmail: false },
  { q: 'Are you proficient in React?', expectType: 'skills', shouldDeferToEmail: false },
  { q: 'What design tools do you use?', expectType: 'skills', shouldDeferToEmail: false },
  { q: 'Can you code?', expectType: 'skills', shouldDeferToEmail: false },
  { q: 'Do you know TypeScript?', expectType: 'skills', shouldDeferToEmail: false },
  { q: 'What programming languages do you know?', expectType: 'skills', shouldDeferToEmail: false },
  { q: 'Are you a developer?', expectType: 'skills', shouldDeferToEmail: false },
  { q: 'Can you do 3D design?', expectType: 'skills', shouldDeferToEmail: false },
  
  // Projects variations
  { q: 'Tell me about her projects', expectType: 'projects', shouldDeferToEmail: false },
  { q: 'Show me your portfolio', expectType: 'projects', shouldDeferToEmail: false },
  { q: 'Tell me about the AI Care Navigator project', expectType: 'projects', shouldDeferToEmail: false },
  { q: 'What about RePack Portal?', expectType: 'projects', shouldDeferToEmail: false },
  { q: 'Give me examples of your work', expectType: 'projects', shouldDeferToEmail: false },
  { q: 'What have you built?', expectType: 'projects', shouldDeferToEmail: false },
  { q: 'Show me case studies', expectType: 'projects', shouldDeferToEmail: false },
  { q: 'What healthcare projects have you done?', expectType: 'projects', shouldDeferToEmail: false },
  { q: 'Tell me about Folio Tracker', expectType: 'projects', shouldDeferToEmail: false },
  { q: 'What projects showcase your skills?', expectType: 'projects', shouldDeferToEmail: false },
  
  // Services variations
  { q: 'What services do you offer?', expectType: 'services', shouldDeferToEmail: false },
  { q: 'Can you help with web design?', expectType: 'services', shouldDeferToEmail: false },
  { q: 'Do you do branding?', expectType: 'services', shouldDeferToEmail: false },
  { q: 'Can you develop websites?', expectType: 'services', shouldDeferToEmail: false },
  { q: 'Do you offer UX consulting?', expectType: 'services', shouldDeferToEmail: false },
  { q: 'Can you design landing pages?', expectType: 'services', shouldDeferToEmail: false },
  { q: 'Do you provide web development?', expectType: 'services', shouldDeferToEmail: false },
  { q: 'Can you help with motion graphics?', expectType: 'services', shouldDeferToEmail: false },
  
  // Contact variations
  { q: 'How can I work with you?', expectType: 'contact', shouldDeferToEmail: false },
  { q: 'How do I contact Karishma?', expectType: 'contact', shouldDeferToEmail: false },
  { q: 'What is your email?', expectType: 'contact', shouldDeferToEmail: false },
  { q: 'How can I hire you?', expectType: 'contact', shouldDeferToEmail: false },
  { q: 'Are you available for collaboration?', expectType: 'contact', shouldDeferToEmail: false },
  { q: 'Where are you located?', expectType: 'contact', shouldDeferToEmail: false },
  { q: 'How do I reach you?', expectType: 'contact', shouldDeferToEmail: false },
  { q: 'Can I get in touch?', expectType: 'contact', shouldDeferToEmail: false },
  
  // Experience
  { q: 'What is her experience?', expectType: 'experience', shouldDeferToEmail: false },
  { q: 'Where did you study?', expectType: 'experience', shouldDeferToEmail: false },
  { q: 'What is your educational background?', expectType: 'experience', shouldDeferToEmail: false },
  { q: 'What university did you attend?', expectType: 'experience', shouldDeferToEmail: false },
  { q: 'What degree do you have?', expectType: 'experience', shouldDeferToEmail: false },
  { q: 'Tell me about your background', expectType: 'experience', shouldDeferToEmail: false },
  
  // Process, pricing, timeline, philosophy
  { q: 'What is your design process?', expectType: 'process', shouldDeferToEmail: false },
  { q: 'How much do you charge?', expectType: 'pricing', shouldDeferToEmail: false },
  { q: 'What are your rates?', expectType: 'pricing', shouldDeferToEmail: false },
  { q: 'How long does a project take?', expectType: 'timeline', shouldDeferToEmail: false },
  { q: 'What is your design philosophy?', expectType: 'philosophy', shouldDeferToEmail: false },
  { q: 'How do you approach projects?', expectType: 'process', shouldDeferToEmail: false },
  { q: 'What is your methodology?', expectType: 'process', shouldDeferToEmail: false },
  
  // === PRIVATE/PERSONAL QUESTIONS (114 questions) ===
  
  // Family & Personal Info (20)
  { q: 'What is her father\'s name?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What is her mother\'s name?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Does she have siblings?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Is she married?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Does she have a boyfriend?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'How old is she?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'When is her birthday?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Where was she born?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What is her address?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Does she have pets?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Does she have a girlfriend?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Is she single?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Is she engaged?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Does she have children?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'How many brothers does she have?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What does her father do?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Where does her family live?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Is her family supportive?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Does she want kids?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What is her relationship status?', expectType: 'personal', shouldDeferToEmail: true },
  
  // Current Work & Status (20)
  { q: 'Where is she working currently?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What is her current job?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Who does she work for?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What company does she work for?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Is she employed?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What project is she working on now?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Is she looking for work?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Is she freelancing?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Does she have a job?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What is she doing right now?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Is she working full-time?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Where does she work?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What is her job title?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Who is her employer?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Is she still a student?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Did she graduate?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Is she working remotely?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What is she doing today?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Is she busy right now?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Where is she right now?', expectType: 'personal', shouldDeferToEmail: true },
  
  // Goals & Future Plans (15)
  { q: 'What are her career goals?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What are her aspirations?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Where does she see herself in 5 years?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What are her future plans?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What is her dream job?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Where does she want to work?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What does she want to achieve?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What are her ambitions?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Where does she see herself in 10 years?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What is her vision?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Does she want to start a business?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Is she planning to move?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What are her next steps?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What companies is she targeting?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Does she want to relocate?', expectType: 'personal', shouldDeferToEmail: true },
  
  // Financial & Compensation (12)
  { q: 'What is her salary?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'How much does she earn?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What is her income?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'How much does she make?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What is her net worth?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'How much is she worth?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What does she earn annually?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Does she make good money?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'How much did she earn last year?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What is her financial status?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Does she have student loans?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'How much debt does she have?', expectType: 'personal', shouldDeferToEmail: true },
  
  // Lifestyle & Preferences (20)
  { q: 'What is her favorite color?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What does she do for fun?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What are her hobbies?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Does she exercise?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Is she vegan?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What is her favorite food?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What is her favorite movie?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What music does she like?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What is her favorite book?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Does she like to travel?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Where does she vacation?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What is her daily routine?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What time does she wake up?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Is she a morning person?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Does she drink coffee?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Does she cook?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What does she eat?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Does she go to the gym?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Does she play sports?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What are her interests?', expectType: 'personal', shouldDeferToEmail: true },
  
  // Health & Medical (12)
  { q: 'Is she healthy?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Does she wear glasses?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Does she have allergies?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Does she take medication?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Does she have health issues?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Is she sick?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What is her height?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What is her weight?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Does she have disabilities?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Does she see a therapist?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'How is her mental health?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Is she stressed?', expectType: 'personal', shouldDeferToEmail: true },
  
  // Social & Relationships (15)
  { q: 'Who are her friends?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Is she introverted or extroverted?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Is she social?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Does she have many friends?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Who is her best friend?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Does she like parties?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Is she on social media?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What is her Instagram?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What is her Twitter?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Who does she follow?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Does she have a mentor?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Who is her mentor?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Who does she look up to?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Who inspires her?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What is her personality like?', expectType: 'personal', shouldDeferToEmail: true },
  
  // === ADDITIONAL 200 QUESTIONS ===
  
  // More Answerable Questions (60 questions)
  { q: 'What makes you different?', expectType: 'skills/philosophy', shouldDeferToEmail: false },
  { q: 'Why should I hire you?', expectType: 'skills/experience', shouldDeferToEmail: false },
  { q: 'Can you work with my team?', expectType: 'contact/services', shouldDeferToEmail: false },
  { q: 'Do you have Figma skills?', expectType: 'skills', shouldDeferToEmail: false },
  { q: 'Are you good at JavaScript?', expectType: 'skills', shouldDeferToEmail: false },
  { q: 'Can you do responsive design?', expectType: 'skills/services', shouldDeferToEmail: false },
  { q: 'Tell me about your tech stack', expectType: 'skills', shouldDeferToEmail: false },
  { q: 'What frameworks do you use?', expectType: 'skills', shouldDeferToEmail: false },
  { q: 'Do you know HTML and CSS?', expectType: 'skills', shouldDeferToEmail: false },
  { q: 'Can you do mobile app design?', expectType: 'services', shouldDeferToEmail: false },
  { q: 'What is your specialty?', expectType: 'skills', shouldDeferToEmail: false },
  { q: 'Are you experienced in UX research?', expectType: 'skills', shouldDeferToEmail: false },
  { q: 'Can you do user testing?', expectType: 'services', shouldDeferToEmail: false },
  { q: 'Do you create prototypes?', expectType: 'services', shouldDeferToEmail: false },
  { q: 'Show me your best work', expectType: 'projects', shouldDeferToEmail: false },
  { q: 'What is your most successful project?', expectType: 'projects', shouldDeferToEmail: false },
  { q: 'Have you worked on healthcare projects?', expectType: 'projects', shouldDeferToEmail: false },
  { q: 'Do you have fintech experience?', expectType: 'projects', shouldDeferToEmail: false },
  { q: 'What industries have you worked in?', expectType: 'projects', shouldDeferToEmail: false },
  { q: 'Can you show sustainability projects?', expectType: 'projects', shouldDeferToEmail: false },
  { q: 'What is your biggest achievement?', expectType: 'projects/experience', shouldDeferToEmail: false },
  { q: 'Tell me about your design work', expectType: 'projects', shouldDeferToEmail: false },
  { q: 'What client work have you done?', expectType: 'projects', shouldDeferToEmail: false },
  { q: 'Do you offer strategy consulting?', expectType: 'services', shouldDeferToEmail: false },
  { q: 'Can you redesign my website?', expectType: 'services', shouldDeferToEmail: false },
  { q: 'Do you do logo design?', expectType: 'services', shouldDeferToEmail: false },
  { q: 'Can you help with visual identity?', expectType: 'services', shouldDeferToEmail: false },
  { q: 'Do you offer ongoing support?', expectType: 'services', shouldDeferToEmail: false },
  { q: 'Can you do WordPress development?', expectType: 'services', shouldDeferToEmail: false },
  { q: 'Do you work with startups?', expectType: 'services', shouldDeferToEmail: false },
  { q: 'Can you help with my app?', expectType: 'services', shouldDeferToEmail: false },
  { q: 'What is your email address?', expectType: 'contact', shouldDeferToEmail: false },
  { q: 'How quickly can you respond?', expectType: 'contact', shouldDeferToEmail: false },
  { q: 'Can we schedule a call?', expectType: 'contact', shouldDeferToEmail: false },
  { q: 'Are you taking new clients?', expectType: 'contact', shouldDeferToEmail: false },
  { q: 'Can I book a consultation?', expectType: 'contact', shouldDeferToEmail: false },
  { q: 'How do we get started?', expectType: 'contact/process', shouldDeferToEmail: false },
  { q: 'What is the next step?', expectType: 'contact/process', shouldDeferToEmail: false },
  { q: 'When did you graduate from Northeastern?', expectType: 'experience', shouldDeferToEmail: false },
  { q: 'What did you major in?', expectType: 'experience', shouldDeferToEmail: false },
  { q: 'Tell me about your education', expectType: 'experience', shouldDeferToEmail: false },
  { q: 'Where have you worked before?', expectType: 'experience', shouldDeferToEmail: false },
  { q: 'What internships have you done?', expectType: 'experience', shouldDeferToEmail: false },
  { q: 'Do you have teaching experience?', expectType: 'experience', shouldDeferToEmail: false },
  { q: 'How do you work?', expectType: 'process', shouldDeferToEmail: false },
  { q: 'What is your workflow?', expectType: 'process', shouldDeferToEmail: false },
  { q: 'How do you handle revisions?', expectType: 'process', shouldDeferToEmail: false },
  { q: 'What is included in your service?', expectType: 'services/pricing', shouldDeferToEmail: false },
  { q: 'What are your payment terms?', expectType: 'pricing', shouldDeferToEmail: false },
  { q: 'Do you offer packages?', expectType: 'pricing', shouldDeferToEmail: false },
  { q: 'What is your hourly rate?', expectType: 'pricing', shouldDeferToEmail: false },
  { q: 'How much for a landing page?', expectType: 'pricing', shouldDeferToEmail: false },
  { q: 'What does a web app cost?', expectType: 'pricing', shouldDeferToEmail: false },
  { q: 'How fast can you deliver?', expectType: 'timeline', shouldDeferToEmail: false },
  { q: 'What is the turnaround time?', expectType: 'timeline', shouldDeferToEmail: false },
  { q: 'When can we launch?', expectType: 'timeline', shouldDeferToEmail: false },
  { q: 'How long for a full project?', expectType: 'timeline', shouldDeferToEmail: false },
  { q: 'Why design matters?', expectType: 'philosophy', shouldDeferToEmail: false },
  { q: 'What is your approach to UX?', expectType: 'philosophy/process', shouldDeferToEmail: false },
  { q: 'How do you ensure quality?', expectType: 'process/philosophy', shouldDeferToEmail: false },
  
  // More Private/Personal Questions (140 questions)
  
  // Extended Family Questions (15)
  { q: 'How many people in her family?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Are her parents still together?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Does she live with her parents?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What does her brother do?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What does her sister do?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Is she close to her siblings?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Where did her parents go to school?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What is her family heritage?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Does she have grandparents?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What is her cultural background?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Is she an immigrant?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What languages does she speak?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Is English her first language?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What is her ethnicity?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What is her religion?', expectType: 'personal', shouldDeferToEmail: true },
  
  // Extended Current Status (20)
  { q: 'Has she found a job yet?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'When did she start her current job?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'How long has she been there?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Does she like her job?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Is she happy at work?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What does she do at work?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Who is her boss?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What team is she on?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Does she have coworkers?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Is she interviewing anywhere?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Has she applied to jobs?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What jobs is she applying for?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Is she job hunting?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Did she get any job offers?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Is she considering any offers?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Will she change jobs?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Is she quitting?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'When will she find work?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What is she doing this month?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What is on her schedule?', expectType: 'personal', shouldDeferToEmail: true },
  
  // Extended Goals/Plans (15)
  { q: 'What is her ultimate goal?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Where does she want to be in 3 years?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What is her career plan?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Does she want to be a manager?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Does she want to be a director?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What role does she want?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Is she targeting FAANG companies?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Does she want to work at Google?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Does she want to work at Apple?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What cities is she considering?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Will she move to San Francisco?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Does she want to stay in Boston?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Is she planning to travel?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What countries does she want to visit?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Does she want to work abroad?', expectType: 'personal', shouldDeferToEmail: true },
  
  // Extended Financial (15)
  { q: 'How much money does she have?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What is her bank balance?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Does she have savings?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'How much has she saved?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Does she invest?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What stocks does she own?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Does she have a 401k?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'How much does she owe?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Does she have credit card debt?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What is her credit score?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Does she own property?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Does she own a house?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Does she rent or own?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'How much is her rent?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Can she afford to live there?', expectType: 'personal', shouldDeferToEmail: true },
  
  // Extended Lifestyle (25)
  { q: 'What does she do on weekends?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'How does she spend her time?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What does she watch on Netflix?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What shows does she like?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What is her favorite series?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Does she watch anime?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What games does she play?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Is she a gamer?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Does she play video games?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What console does she have?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Does she read books?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What is she reading now?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What genre does she like?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Does she listen to podcasts?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What podcasts does she like?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What is her Spotify?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What artists does she listen to?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Does she go to concerts?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Has she been to festivals?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Does she drink alcohol?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Does she smoke?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Does she party?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Does she go clubbing?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What bars does she go to?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Where does she hang out?', expectType: 'personal', shouldDeferToEmail: true },
  
  // Extended Health (15)
  { q: 'Does she have insurance?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What doctor does she see?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'When was her last checkup?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Is she on any medication?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Does she have anxiety?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Does she have depression?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Is she seeing a therapist?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'How is she mentally?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Is she ok?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Is she doing well?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'How is she feeling?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Is she tired?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Does she sleep well?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Does she have insomnia?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'How many hours does she sleep?', expectType: 'personal', shouldDeferToEmail: true },
  
  // Extended Social (20)
  { q: 'Does she date?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Is she on dating apps?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Is she on Tinder?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Is she on Bumble?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Who is she dating?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Does she have a partner?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Who is her significant other?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'How long has she been dating?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'When did she start dating?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Has she been in relationships?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Who was her last boyfriend?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Who was her ex?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'When did they break up?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Why did they break up?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Is she over her ex?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Does she want a relationship?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Is she looking to date?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What is her type?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What does she look for in a partner?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Is she interested in anyone?', expectType: 'personal', shouldDeferToEmail: true },
  
  // Miscellaneous Personal (15)
  { q: 'What car does she drive?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Does she own a car?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Can she drive?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Does she have a license?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'How does she get around?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Does she take the T?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Does she bike?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Does she walk to work?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What phone does she have?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Does she have an iPhone?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What laptop does she use?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Does she have a MacBook?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What is her setup like?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Where does she work from?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Does she have a home office?', expectType: 'personal', shouldDeferToEmail: true },
  
  // === ADDITIONAL 200 QUESTIONS (150 Answerable + 50 Personal) ===
  
  // Answerable - Skills Deep Dive (30)
  { q: 'Do you use Adobe XD?', expectType: 'skills', shouldDeferToEmail: false },
  { q: 'Can you work with Sketch?', expectType: 'skills', shouldDeferToEmail: false },
  { q: 'Are you familiar with Redux?', expectType: 'skills', shouldDeferToEmail: false },
  { q: 'Do you know Sass?', expectType: 'skills', shouldDeferToEmail: false },
  { q: 'Can you use Bootstrap?', expectType: 'skills', shouldDeferToEmail: false },
  { q: 'Do you have prototyping skills?', expectType: 'skills', shouldDeferToEmail: false },
  { q: 'Are you good with Adobe Creative Suite?', expectType: 'skills', shouldDeferToEmail: false },
  { q: 'Can you do wireframing?', expectType: 'skills', shouldDeferToEmail: false },
  { q: 'Do you know user research?', expectType: 'skills', shouldDeferToEmail: false },
  { q: 'Can you do accessibility design?', expectType: 'skills', shouldDeferToEmail: false },
  { q: 'Are you familiar with design systems?', expectType: 'skills', shouldDeferToEmail: false },
  { q: 'Do you know front-end development?', expectType: 'skills', shouldDeferToEmail: false },
  { q: 'Can you do responsive development?', expectType: 'skills', shouldDeferToEmail: false },
  { q: 'Are you skilled in animation?', expectType: 'skills', shouldDeferToEmail: false },
  { q: 'Do you have interaction design skills?', expectType: 'skills', shouldDeferToEmail: false },
  { q: 'Can you do information architecture?', expectType: 'skills', shouldDeferToEmail: false },
  { q: 'Are you good at visual design?', expectType: 'skills', shouldDeferToEmail: false },
  { q: 'Do you know product design?', expectType: 'skills', shouldDeferToEmail: false },
  { q: 'Can you create design documentation?', expectType: 'skills', shouldDeferToEmail: false },
  { q: 'Are you experienced with usability testing?', expectType: 'skills', shouldDeferToEmail: false },
  { q: 'Do you understand design thinking?', expectType: 'skills', shouldDeferToEmail: false },
  { q: 'Can you work with APIs?', expectType: 'skills', shouldDeferToEmail: false },
  { q: 'Are you familiar with Git?', expectType: 'skills', shouldDeferToEmail: false },
  { q: 'Do you know version control?', expectType: 'skills', shouldDeferToEmail: false },
  { q: 'Can you do A/B testing?', expectType: 'skills', shouldDeferToEmail: false },
  { q: 'Are you good at data visualization?', expectType: 'skills', shouldDeferToEmail: false },
  { q: 'Do you have mobile design experience?', expectType: 'skills', shouldDeferToEmail: false },
  { q: 'Can you design for iOS?', expectType: 'skills', shouldDeferToEmail: false },
  { q: 'Do you know Android design?', expectType: 'skills', shouldDeferToEmail: false },
  { q: 'Are you familiar with component libraries?', expectType: 'skills', shouldDeferToEmail: false },
  
  // Answerable - Projects & Portfolio (25)
  { q: 'How did AI Care Navigator help patients?', expectType: 'projects', shouldDeferToEmail: false },
  { q: 'What impact did RePack Portal have?', expectType: 'projects', shouldDeferToEmail: false },
  { q: 'Tell me more about Folio Tracker', expectType: 'projects', shouldDeferToEmail: false },
  { q: 'What problem did AI Care Navigator solve?', expectType: 'projects', shouldDeferToEmail: false },
  { q: 'How does RePack Portal work?', expectType: 'projects', shouldDeferToEmail: false },
  { q: 'What features does Folio Tracker have?', expectType: 'projects', shouldDeferToEmail: false },
  { q: 'Show me your design portfolio', expectType: 'projects', shouldDeferToEmail: false },
  { q: 'What results did your projects achieve?', expectType: 'projects', shouldDeferToEmail: false },
  { q: 'Can you show healthcare design examples?', expectType: 'projects', shouldDeferToEmail: false },
  { q: 'Do you have ecommerce projects?', expectType: 'projects', shouldDeferToEmail: false },
  { q: 'Have you built dashboards?', expectType: 'projects', shouldDeferToEmail: false },
  { q: 'Show me your UI work', expectType: 'projects', shouldDeferToEmail: false },
  { q: 'What UX projects have you done?', expectType: 'projects', shouldDeferToEmail: false },
  { q: 'Can I see your development work?', expectType: 'projects', shouldDeferToEmail: false },
  { q: 'Have you worked on SaaS products?', expectType: 'projects', shouldDeferToEmail: false },
  { q: 'Do you have B2B project examples?', expectType: 'projects', shouldDeferToEmail: false },
  { q: 'Show me your recent work', expectType: 'projects', shouldDeferToEmail: false },
  { q: 'What was your favorite project?', expectType: 'projects', shouldDeferToEmail: false },
  { q: 'Which project are you most proud of?', expectType: 'projects', shouldDeferToEmail: false },
  { q: 'Have you done marketplace design?', expectType: 'projects', shouldDeferToEmail: false },
  { q: 'Show me platform projects', expectType: 'projects', shouldDeferToEmail: false },
  { q: 'Do you have app design examples?', expectType: 'projects', shouldDeferToEmail: false },
  { q: 'Have you built analytics dashboards?', expectType: 'projects', shouldDeferToEmail: false },
  { q: 'What enterprise projects have you done?', expectType: 'projects', shouldDeferToEmail: false },
  { q: 'Can you show your problem-solving approach?', expectType: 'projects', shouldDeferToEmail: false },
  
  // Answerable - Services & Offerings (25)
  { q: 'Do you offer UX audits?', expectType: 'services', shouldDeferToEmail: false },
  { q: 'Can you do competitive analysis?', expectType: 'services', shouldDeferToEmail: false },
  { q: 'Do you create user personas?', expectType: 'services', shouldDeferToEmail: false },
  { q: 'Can you do user journey mapping?', expectType: 'services', shouldDeferToEmail: false },
  { q: 'Do you offer design sprints?', expectType: 'services', shouldDeferToEmail: false },
  { q: 'Can you help with MVP design?', expectType: 'services', shouldDeferToEmail: false },
  { q: 'Do you do product strategy?', expectType: 'services', shouldDeferToEmail: false },
  { q: 'Can you redesign existing products?', expectType: 'services', shouldDeferToEmail: false },
  { q: 'Do you offer maintenance?', expectType: 'services', shouldDeferToEmail: false },
  { q: 'Can you do design handoff?', expectType: 'services', shouldDeferToEmail: false },
  { q: 'Do you work with developers?', expectType: 'services', shouldDeferToEmail: false },
  { q: 'Can you join existing teams?', expectType: 'services', shouldDeferToEmail: false },
  { q: 'Do you offer workshops?', expectType: 'services', shouldDeferToEmail: false },
  { q: 'Can you train teams?', expectType: 'services', shouldDeferToEmail: false },
  { q: 'Do you do design reviews?', expectType: 'services', shouldDeferToEmail: false },
  { q: 'Can you help with branding strategy?', expectType: 'services', shouldDeferToEmail: false },
  { q: 'Do you create style guides?', expectType: 'services', shouldDeferToEmail: false },
  { q: 'Can you build design systems?', expectType: 'services', shouldDeferToEmail: false },
  { q: 'Do you offer illustration services?', expectType: 'services', shouldDeferToEmail: false },
  { q: 'Can you do icon design?', expectType: 'services', shouldDeferToEmail: false },
  { q: 'Do you create marketing materials?', expectType: 'services', shouldDeferToEmail: false },
  { q: 'Can you design presentations?', expectType: 'services', shouldDeferToEmail: false },
  { q: 'Do you offer CMS development?', expectType: 'services', shouldDeferToEmail: false },
  { q: 'Can you do SEO optimization?', expectType: 'services', shouldDeferToEmail: false },
  { q: 'Do you provide hosting setup?', expectType: 'services', shouldDeferToEmail: false },
  
  // Answerable - Process & Methodology (20)
  { q: 'How do you start a project?', expectType: 'process', shouldDeferToEmail: false },
  { q: 'What is your research process?', expectType: 'process', shouldDeferToEmail: false },
  { q: 'How do you gather requirements?', expectType: 'process', shouldDeferToEmail: false },
  { q: 'What is your design thinking approach?', expectType: 'process', shouldDeferToEmail: false },
  { q: 'How do you validate designs?', expectType: 'process', shouldDeferToEmail: false },
  { q: 'Do you do iterative design?', expectType: 'process', shouldDeferToEmail: false },
  { q: 'How do you handle feedback?', expectType: 'process', shouldDeferToEmail: false },
  { q: 'What is your collaboration style?', expectType: 'process', shouldDeferToEmail: false },
  { q: 'How do you communicate with clients?', expectType: 'process', shouldDeferToEmail: false },
  { q: 'What deliverables do you provide?', expectType: 'process', shouldDeferToEmail: false },
  { q: 'How many revisions do you offer?', expectType: 'process', shouldDeferToEmail: false },
  { q: 'What is your typical timeline?', expectType: 'process', shouldDeferToEmail: false },
  { q: 'How do you prioritize features?', expectType: 'process', shouldDeferToEmail: false },
  { q: 'What tools do you use for collaboration?', expectType: 'process', shouldDeferToEmail: false },
  { q: 'How do you ensure quality?', expectType: 'process', shouldDeferToEmail: false },
  { q: 'Do you follow agile methodology?', expectType: 'process', shouldDeferToEmail: false },
  { q: 'How do you measure success?', expectType: 'process', shouldDeferToEmail: false },
  { q: 'What metrics do you track?', expectType: 'process', shouldDeferToEmail: false },
  { q: 'How do you test designs?', expectType: 'process', shouldDeferToEmail: false },
  { q: 'What is your QA process?', expectType: 'process', shouldDeferToEmail: false },
  
  // Answerable - Pricing & Business (15)
  { q: 'Do you have a minimum project size?', expectType: 'pricing', shouldDeferToEmail: false },
  { q: 'What is your pricing model?', expectType: 'pricing', shouldDeferToEmail: false },
  { q: 'Do you offer fixed price projects?', expectType: 'pricing', shouldDeferToEmail: false },
  { q: 'Can I pay monthly?', expectType: 'pricing', shouldDeferToEmail: false },
  { q: 'Do you require a deposit?', expectType: 'pricing', shouldDeferToEmail: false },
  { q: 'What payment methods do you accept?', expectType: 'pricing', shouldDeferToEmail: false },
  { q: 'Do you offer payment plans?', expectType: 'pricing', shouldDeferToEmail: false },
  { q: 'Can you work within my budget?', expectType: 'pricing', shouldDeferToEmail: false },
  { q: 'What does your pricing include?', expectType: 'pricing', shouldDeferToEmail: false },
  { q: 'Are there any additional costs?', expectType: 'pricing', shouldDeferToEmail: false },
  { q: 'Do you charge for revisions?', expectType: 'pricing', shouldDeferToEmail: false },
  { q: 'What is your cancellation policy?', expectType: 'pricing', shouldDeferToEmail: false },
  { q: 'Do you offer refunds?', expectType: 'pricing', shouldDeferToEmail: false },
  { q: 'Can you provide a quote?', expectType: 'pricing', shouldDeferToEmail: false },
  { q: 'How do you estimate projects?', expectType: 'pricing', shouldDeferToEmail: false },
  
  // Answerable - Timeline & Availability (10)
  { q: 'How soon can you start?', expectType: 'timeline', shouldDeferToEmail: false },
  { q: 'What is your current availability?', expectType: 'timeline', shouldDeferToEmail: false },
  { q: 'How long for a simple website?', expectType: 'timeline', shouldDeferToEmail: false },
  { q: 'Can you meet tight deadlines?', expectType: 'timeline', shouldDeferToEmail: false },
  { q: 'What is the minimum project duration?', expectType: 'timeline', shouldDeferToEmail: false },
  { q: 'How long does discovery take?', expectType: 'timeline', shouldDeferToEmail: false },
  { q: 'When can you deliver?', expectType: 'timeline', shouldDeferToEmail: false },
  { q: 'How quickly can you prototype?', expectType: 'timeline', shouldDeferToEmail: false },
  { q: 'What is your lead time?', expectType: 'timeline', shouldDeferToEmail: false },
  { q: 'Can you do rush projects?', expectType: 'timeline', shouldDeferToEmail: false },
  
  // Answerable - Contact & Logistics (15)
  { q: 'Where can I see your work?', expectType: 'contact/projects', shouldDeferToEmail: false },
  { q: 'Do you have a portfolio website?', expectType: 'contact', shouldDeferToEmail: false },
  { q: 'How do I send you a message?', expectType: 'contact', shouldDeferToEmail: false },
  { q: 'Can we have a discovery call?', expectType: 'contact', shouldDeferToEmail: false },
  { q: 'Do you meet in person?', expectType: 'contact', shouldDeferToEmail: false },
  { q: 'Can we work remotely?', expectType: 'contact', shouldDeferToEmail: false },
  { q: 'What timezone are you in?', expectType: 'contact', shouldDeferToEmail: false },
  { q: 'Do you work with international clients?', expectType: 'contact', shouldDeferToEmail: false },
  { q: 'Can you travel for projects?', expectType: 'contact', shouldDeferToEmail: false },
  { q: 'How do I get started with you?', expectType: 'contact', shouldDeferToEmail: false },
  { q: 'What information do you need?', expectType: 'contact/process', shouldDeferToEmail: false },
  { q: 'Do you sign NDAs?', expectType: 'contact', shouldDeferToEmail: false },
  { q: 'Can you provide references?', expectType: 'contact', shouldDeferToEmail: false },
  { q: 'Do you have testimonials?', expectType: 'contact', shouldDeferToEmail: false },
  { q: 'How can I verify your work?', expectType: 'contact/projects', shouldDeferToEmail: false },
  
  // Answerable - Philosophy & Approach (10)
  { q: 'What is your design philosophy?', expectType: 'philosophy', shouldDeferToEmail: false },
  { q: 'Why is UX important?', expectType: 'philosophy', shouldDeferToEmail: false },
  { q: 'How do you define good design?', expectType: 'philosophy', shouldDeferToEmail: false },
  { q: 'What makes a great product?', expectType: 'philosophy', shouldDeferToEmail: false },
  { q: 'How do you balance aesthetics and function?', expectType: 'philosophy', shouldDeferToEmail: false },
  { q: 'What is your approach to user-centered design?', expectType: 'philosophy', shouldDeferToEmail: false },
  { q: 'Why should I choose you?', expectType: 'philosophy', shouldDeferToEmail: false },
  { q: 'What makes you unique?', expectType: 'philosophy', shouldDeferToEmail: false },
  { q: 'How do you stay current with trends?', expectType: 'philosophy', shouldDeferToEmail: false },
  { q: 'What inspires your work?', expectType: 'philosophy', shouldDeferToEmail: false },
  
  // Personal/Unanswerable (50 questions)
  { q: 'What time does she go to bed?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Does she have a morning routine?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What does she eat for breakfast?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Is she a coffee or tea person?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Does she work out in the morning?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What gym does she go to?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Does she meditate?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What does she do to relax?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Is she spiritual?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Does she practice yoga?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What is her zodiac sign?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Does she believe in astrology?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What are her political views?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Who did she vote for?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Is she liberal or conservative?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What causes does she support?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Does she volunteer?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What charities does she donate to?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Is she an activist?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What social issues matter to her?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Does she have roommates?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Who does she live with?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Does she live alone?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'How big is her apartment?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What neighborhood does she live in?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Does she like her neighborhood?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'How long has she lived there?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Is she planning to move?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Where would she like to live?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Does she want to buy a house?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What is her biggest fear?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What is her biggest regret?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What is her greatest strength?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What is her weakness?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'How does she handle stress?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What makes her angry?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What makes her sad?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What makes her laugh?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Is she an optimist or pessimist?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'How does she deal with failure?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What motivates her daily?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What keeps her going?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What are her daily struggles?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Does she have work-life balance?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'How many hours does she work per day?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Does she work on weekends?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Does she take vacations?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Where did she last vacation?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What is her bucket list?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'If she could live anywhere, where?', expectType: 'personal', shouldDeferToEmail: true },
  
  // === NEW 500 TEST CASES: 250 ANSWERABLE + 250 PERSONAL ===
  
  // ANSWERABLE: Skills (25)
  { q: 'Do you use Adobe Creative Suite?', expectType: 'skills', shouldDeferToEmail: false },
  { q: 'Are you familiar with Figma?', expectType: 'skills', shouldDeferToEmail: false },
  { q: 'Can you work with Sketch?', expectType: 'skills', shouldDeferToEmail: false },
  { q: 'Do you know Redux?', expectType: 'skills', shouldDeferToEmail: false },
  { q: 'Are you experienced with Sass?', expectType: 'skills', shouldDeferToEmail: false },
  { q: 'Do you know Bootstrap?', expectType: 'skills', shouldDeferToEmail: false },
  { q: 'Can you prototype?', expectType: 'skills', shouldDeferToEmail: false },
  { q: 'Are you good with Git?', expectType: 'skills', shouldDeferToEmail: false },
  { q: 'Do you do user research?', expectType: 'skills', shouldDeferToEmail: false },
  { q: 'Can you implement accessibility?', expectType: 'skills', shouldDeferToEmail: false },
  { q: 'Are you familiar with design systems?', expectType: 'skills', shouldDeferToEmail: false },
  { q: 'Do you have front-end experience?', expectType: 'skills', shouldDeferToEmail: false },
  { q: 'Can you create responsive designs?', expectType: 'skills', shouldDeferToEmail: false },
  { q: 'Do you work with animations?', expectType: 'skills', shouldDeferToEmail: false },
  { q: 'Are you experienced in interaction design?', expectType: 'skills', shouldDeferToEmail: false },
  { q: 'Can you do information architecture?', expectType: 'skills', shouldDeferToEmail: false },
  { q: 'Do you specialize in visual design?', expectType: 'skills', shouldDeferToEmail: false },
  { q: 'Can you handle product design?', expectType: 'skills', shouldDeferToEmail: false },
  { q: 'Do you write design documentation?', expectType: 'skills', shouldDeferToEmail: false },
  { q: 'Are you familiar with usability testing?', expectType: 'skills', shouldDeferToEmail: false },
  { q: 'Do you apply design thinking?', expectType: 'skills', shouldDeferToEmail: false },
  { q: 'Can you work with REST APIs?', expectType: 'skills', shouldDeferToEmail: false },
  { q: 'Do you know version control?', expectType: 'skills', shouldDeferToEmail: false },
  { q: 'Can you do A/B testing?', expectType: 'skills', shouldDeferToEmail: false },
  { q: 'Do you do data visualization?', expectType: 'skills', shouldDeferToEmail: false },
  
  // ANSWERABLE: Projects (25)
  { q: 'What healthcare projects have you completed?', expectType: 'projects', shouldDeferToEmail: false },
  { q: 'Can you show me sustainable design work?', expectType: 'projects', shouldDeferToEmail: false },
  { q: 'Tell me about your financial dashboard projects', expectType: 'projects', shouldDeferToEmail: false },
  { q: 'What is the biggest achievement in your portfolio?', expectType: 'projects', shouldDeferToEmail: false },
  { q: 'What is your best work?', expectType: 'projects', shouldDeferToEmail: false },
  { q: 'Which industries have you worked in?', expectType: 'projects', shouldDeferToEmail: false },
  { q: 'Do you have fintech experience?', expectType: 'projects', shouldDeferToEmail: false },
  { q: 'What client work have you done?', expectType: 'projects', shouldDeferToEmail: false },
  { q: 'Show me your recent work', expectType: 'projects', shouldDeferToEmail: false },
  { q: 'What is on your portfolio?', expectType: 'projects', shouldDeferToEmail: false },
  { q: 'Do you have SaaS experience?', expectType: 'projects', shouldDeferToEmail: false },
  { q: 'Tell me about AI Care Navigator', expectType: 'projects', shouldDeferToEmail: false },
  { q: 'What features does RePack Portal have?', expectType: 'projects', shouldDeferToEmail: false },
  { q: 'How many projects have you shipped?', expectType: 'projects', shouldDeferToEmail: false },
  { q: 'What types of applications have you designed?', expectType: 'projects', shouldDeferToEmail: false },
  { q: 'Do you have startup experience?', expectType: 'projects', shouldDeferToEmail: false },
  { q: 'What scale of products have you worked on?', expectType: 'projects', shouldDeferToEmail: false },
  { q: 'Can you show me mobile app designs?', expectType: 'projects', shouldDeferToEmail: false },
  { q: 'What is your most complex project?', expectType: 'projects', shouldDeferToEmail: false },
  { q: 'Do you have e-commerce experience?', expectType: 'projects', shouldDeferToEmail: false },
  { q: 'Tell me about cross-platform projects', expectType: 'projects', shouldDeferToEmail: false },
  { q: 'What B2B products have you designed?', expectType: 'projects', shouldDeferToEmail: false },
  { q: 'Do you have B2C experience?', expectType: 'projects', shouldDeferToEmail: false },
  { q: 'What data visualization work have you done?', expectType: 'projects', shouldDeferToEmail: false },
  { q: 'Show me your most recent project', expectType: 'projects', shouldDeferToEmail: false },
  
  // ANSWERABLE: Services (25)
  { q: 'Do you offer UX audits?', expectType: 'services', shouldDeferToEmail: false },
  { q: 'Can you do competitive analysis?', expectType: 'services', shouldDeferToEmail: false },
  { q: 'Do you create user personas?', expectType: 'services', shouldDeferToEmail: false },
  { q: 'Can you map customer journeys?', expectType: 'services', shouldDeferToEmail: false },
  { q: 'Do you run design sprints?', expectType: 'services', shouldDeferToEmail: false },
  { q: 'Can you help with MVP development?', expectType: 'services', shouldDeferToEmail: false },
  { q: 'Do you offer product strategy?', expectType: 'services', shouldDeferToEmail: false },
  { q: 'Can you redesign existing products?', expectType: 'services', shouldDeferToEmail: false },
  { q: 'Do you provide maintenance?', expectType: 'services', shouldDeferToEmail: false },
  { q: 'Can you do design handoffs?', expectType: 'services', shouldDeferToEmail: false },
  { q: 'Do you run workshops?', expectType: 'services', shouldDeferToEmail: false },
  { q: 'Can you train teams?', expectType: 'services', shouldDeferToEmail: false },
  { q: 'Do you do design reviews?', expectType: 'services', shouldDeferToEmail: false },
  { q: 'Can you develop branding strategy?', expectType: 'services', shouldDeferToEmail: false },
  { q: 'Do you create style guides?', expectType: 'services', shouldDeferToEmail: false },
  { q: 'Can you build design systems?', expectType: 'services', shouldDeferToEmail: false },
  { q: 'Do you do illustration work?', expectType: 'services', shouldDeferToEmail: false },
  { q: 'Can you design icons?', expectType: 'services', shouldDeferToEmail: false },
  { q: 'Do you create marketing materials?', expectType: 'services', shouldDeferToEmail: false },
  { q: 'Can you make presentations?', expectType: 'services', shouldDeferToEmail: false },
  { q: 'Do you work with CMS?', expectType: 'services', shouldDeferToEmail: false },
  { q: 'Can you optimize for SEO?', expectType: 'services', shouldDeferToEmail: false },
  { q: 'Do you handle web hosting?', expectType: 'services', shouldDeferToEmail: false },
  { q: 'Can you support existing projects?', expectType: 'services', shouldDeferToEmail: false },
  { q: 'Do you offer full-stack?', expectType: 'services', shouldDeferToEmail: false },
  { q: 'Where did you study?', expectType: 'experience', shouldDeferToEmail: false },
  { q: 'What degree do you have?', expectType: 'experience', shouldDeferToEmail: false },
  { q: 'What was your major?', expectType: 'experience', shouldDeferToEmail: false },
  { q: 'Tell me about your education', expectType: 'experience', shouldDeferToEmail: false },
  { q: 'Do you have a design degree?', expectType: 'experience', shouldDeferToEmail: false },
  { q: 'Where did you graduate?', expectType: 'experience', shouldDeferToEmail: false },
  { q: 'What universities did you attend?', expectType: 'experience', shouldDeferToEmail: false },
  { q: 'Do you have formal training?', expectType: 'experience', shouldDeferToEmail: false },
  { q: 'Tell me about your internships', expectType: 'experience', shouldDeferToEmail: false },
  { q: 'What is your background?', expectType: 'experience', shouldDeferToEmail: false },
  { q: 'How many years of experience?', expectType: 'experience', shouldDeferToEmail: false },
  { q: 'Where have you worked?', expectType: 'experience', shouldDeferToEmail: false },
  { q: 'What companies have you worked for?', expectType: 'experience', shouldDeferToEmail: false },
  { q: 'Have you worked at startups?', expectType: 'experience', shouldDeferToEmail: false },
  { q: 'Have you worked at tech companies?', expectType: 'experience', shouldDeferToEmail: false },
  { q: 'What certifications do you have?', expectType: 'experience', shouldDeferToEmail: false },
  { q: 'Tell me about teaching experience', expectType: 'experience', shouldDeferToEmail: false },
  { q: 'Have you mentored others?', expectType: 'experience', shouldDeferToEmail: false },
  { q: 'What makes you qualified?', expectType: 'experience', shouldDeferToEmail: false },
  { q: 'Can you share qualifications?', expectType: 'experience', shouldDeferToEmail: false },
  { q: 'What is your design process?', expectType: 'process', shouldDeferToEmail: false },
  { q: 'How do you approach projects?', expectType: 'process', shouldDeferToEmail: false },
  { q: 'What is your methodology?', expectType: 'process', shouldDeferToEmail: false },
  { q: 'How do you start a project?', expectType: 'process', shouldDeferToEmail: false },
  { q: 'What is your research process?', expectType: 'process', shouldDeferToEmail: false },
  { q: 'How do you gather requirements?', expectType: 'process', shouldDeferToEmail: false },
  { q: 'How do you validate designs?', expectType: 'process', shouldDeferToEmail: false },
  { q: 'Do you use design thinking?', expectType: 'process', shouldDeferToEmail: false },
  { q: 'What is your iterative process?', expectType: 'process', shouldDeferToEmail: false },
  { q: 'How do you handle feedback?', expectType: 'process', shouldDeferToEmail: false },
  { q: 'How do you collaborate?', expectType: 'process', shouldDeferToEmail: false },
  { q: 'How do you communicate?', expectType: 'process', shouldDeferToEmail: false },
  { q: 'What deliverables do you provide?', expectType: 'process', shouldDeferToEmail: false },
  { q: 'How do you prioritize?', expectType: 'process', shouldDeferToEmail: false },
  { q: 'What tools do you use?', expectType: 'process', shouldDeferToEmail: false },
  { q: 'How do you ensure quality?', expectType: 'process', shouldDeferToEmail: false },
  { q: 'Do you follow agile?', expectType: 'process', shouldDeferToEmail: false },
  { q: 'How do you measure success?', expectType: 'process', shouldDeferToEmail: false },
  { q: 'What metrics do you track?', expectType: 'process', shouldDeferToEmail: false },
  { q: 'How do you test designs?', expectType: 'process', shouldDeferToEmail: false },
  { q: 'What is your pricing model?', expectType: 'pricing', shouldDeferToEmail: false },
  { q: 'How much do you charge?', expectType: 'pricing', shouldDeferToEmail: false },
  { q: 'What is your rate?', expectType: 'pricing', shouldDeferToEmail: false },
  { q: 'Do you have minimum budget?', expectType: 'pricing', shouldDeferToEmail: false },
  { q: 'Do you offer fixed price?', expectType: 'pricing', shouldDeferToEmail: false },
  { q: 'Can I pay monthly?', expectType: 'pricing', shouldDeferToEmail: false },
  { q: 'What is the deposit?', expectType: 'pricing', shouldDeferToEmail: false },
  { q: 'How do you handle payments?', expectType: 'pricing', shouldDeferToEmail: false },
  { q: 'What payment methods?', expectType: 'pricing', shouldDeferToEmail: false },
  { q: 'Do you offer payment plans?', expectType: 'pricing', shouldDeferToEmail: false },
  { q: 'Can you work within budget?', expectType: 'pricing', shouldDeferToEmail: false },
  { q: 'What does pricing include?', expectType: 'pricing', shouldDeferToEmail: false },
  { q: 'Are there additional costs?', expectType: 'pricing', shouldDeferToEmail: false },
  { q: 'How much for revisions?', expectType: 'pricing', shouldDeferToEmail: false },
  { q: 'What is cancellation policy?', expectType: 'pricing', shouldDeferToEmail: false },
  { q: 'Do you offer refunds?', expectType: 'pricing', shouldDeferToEmail: false },
  { q: 'Can you provide a quote?', expectType: 'pricing', shouldDeferToEmail: false },
  { q: 'What is cost estimate?', expectType: 'pricing', shouldDeferToEmail: false },
  { q: 'How is pricing calculated?', expectType: 'pricing', shouldDeferToEmail: false },
  { q: 'What is included in investment?', expectType: 'pricing', shouldDeferToEmail: false },
  { q: 'When are you available?', expectType: 'timeline', shouldDeferToEmail: false },
  { q: 'How long does a project take?', expectType: 'timeline', shouldDeferToEmail: false },
  { q: 'What is your timeline?', expectType: 'timeline', shouldDeferToEmail: false },
  { q: 'How long for website?', expectType: 'timeline', shouldDeferToEmail: false },
  { q: 'Can you meet tight deadline?', expectType: 'timeline', shouldDeferToEmail: false },
  { q: 'How soon can launch?', expectType: 'timeline', shouldDeferToEmail: false },
  { q: 'What is minimum duration?', expectType: 'timeline', shouldDeferToEmail: false },
  { q: 'How long does discovery take?', expectType: 'timeline', shouldDeferToEmail: false },
  { q: 'When can you deliver?', expectType: 'timeline', shouldDeferToEmail: false },
  { q: 'How quickly can prototype?', expectType: 'timeline', shouldDeferToEmail: false },
  { q: 'What is lead time?', expectType: 'timeline', shouldDeferToEmail: false },
  { q: 'Can you rush a project?', expectType: 'timeline', shouldDeferToEmail: false },
  { q: 'What is turnaround time?', expectType: 'timeline', shouldDeferToEmail: false },
  { q: 'How long for branding?', expectType: 'timeline', shouldDeferToEmail: false },
  { q: 'What is design duration?', expectType: 'timeline', shouldDeferToEmail: false },
  { q: 'How long for development?', expectType: 'timeline', shouldDeferToEmail: false },
  { q: 'When will project be done?', expectType: 'timeline', shouldDeferToEmail: false },
  { q: 'What is your availability?', expectType: 'timeline', shouldDeferToEmail: false },
  { q: 'Are you taking new projects?', expectType: 'timeline', shouldDeferToEmail: false },
  { q: 'When can we start?', expectType: 'timeline', shouldDeferToEmail: false },
  { q: 'Where can I see your work?', expectType: 'contact', shouldDeferToEmail: false },
  { q: 'How can I send message?', expectType: 'contact', shouldDeferToEmail: false },
  { q: 'What information needed?', expectType: 'contact', shouldDeferToEmail: false },
  { q: 'How can I verify work?', expectType: 'contact', shouldDeferToEmail: false },
  { q: 'Do you have portfolio site?', expectType: 'contact', shouldDeferToEmail: false },
  { q: 'Can we schedule discovery call?', expectType: 'contact', shouldDeferToEmail: false },
  { q: 'Can I meet in person?', expectType: 'contact', shouldDeferToEmail: false },
  { q: 'Do you work remotely?', expectType: 'contact', shouldDeferToEmail: false },
  { q: 'What is your timezone?', expectType: 'contact', shouldDeferToEmail: false },
  { q: 'Do you work internationally?', expectType: 'contact', shouldDeferToEmail: false },
  { q: 'Do you travel?', expectType: 'contact', shouldDeferToEmail: false },
  { q: 'Do you sign NDAs?', expectType: 'contact', shouldDeferToEmail: false },
  { q: 'Can you provide references?', expectType: 'contact', shouldDeferToEmail: false },
  { q: 'Do you have testimonials?', expectType: 'contact', shouldDeferToEmail: false },
  { q: 'Are you on LinkedIn?', expectType: 'contact', shouldDeferToEmail: false },
  { q: 'Do you have GitHub?', expectType: 'contact', shouldDeferToEmail: false },
  { q: 'What social media?', expectType: 'contact', shouldDeferToEmail: false },
  { q: 'How quick do you respond?', expectType: 'contact', shouldDeferToEmail: false },
  { q: 'What is response time?', expectType: 'contact', shouldDeferToEmail: false },
  { q: 'Can I view full portfolio?', expectType: 'contact', shouldDeferToEmail: false },
  { q: 'How do I book?', expectType: 'contact', shouldDeferToEmail: false },
  { q: 'What is LinkedIn?', expectType: 'contact', shouldDeferToEmail: false },
  { q: 'Do you have Behance?', expectType: 'contact', shouldDeferToEmail: false },
  { q: 'Can I see case studies?', expectType: 'contact', shouldDeferToEmail: false },
  { q: 'How do I start?', expectType: 'contact', shouldDeferToEmail: false },
  { q: 'What is your philosophy?', expectType: 'philosophy', shouldDeferToEmail: false },
  { q: 'Why is UX important?', expectType: 'philosophy', shouldDeferToEmail: false },
  { q: 'How do you define design?', expectType: 'philosophy', shouldDeferToEmail: false },
  { q: 'What makes great product?', expectType: 'philosophy', shouldDeferToEmail: false },
  { q: 'How balance aesthetics?', expectType: 'philosophy', shouldDeferToEmail: false },
  { q: 'Do you believe UCD?', expectType: 'philosophy', shouldDeferToEmail: false },
  { q: 'Why use your services?', expectType: 'philosophy', shouldDeferToEmail: false },
  { q: 'What makes you unique?', expectType: 'philosophy', shouldDeferToEmail: false },
  { q: 'How stay current?', expectType: 'philosophy', shouldDeferToEmail: false },
  { q: 'What inspires you?', expectType: 'philosophy', shouldDeferToEmail: false },
  { q: 'Do you believe learning?', expectType: 'philosophy', shouldDeferToEmail: false },
  { q: 'What problem solving?', expectType: 'philosophy', shouldDeferToEmail: false },
  { q: 'How approach innovation?', expectType: 'philosophy', shouldDeferToEmail: false },
  { q: 'What drives you?', expectType: 'philosophy', shouldDeferToEmail: false },
  { q: 'Do you focus satisfaction?', expectType: 'philosophy', shouldDeferToEmail: false },
  { q: 'What is your vision?', expectType: 'philosophy', shouldDeferToEmail: false },
  { q: 'How define success?', expectType: 'philosophy', shouldDeferToEmail: false },
  { q: 'Do you believe data-driven?', expectType: 'philosophy', shouldDeferToEmail: false },
  { q: 'What values?', expectType: 'philosophy', shouldDeferToEmail: false },
  { q: 'Why do design?', expectType: 'philosophy', shouldDeferToEmail: false },
  { q: 'Tell me about family', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Who are parents?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Do you have siblings?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'How many siblings?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Is she married?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Is she in relationship?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What do for fun?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What are hobbies?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What time wake up?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What daily routine?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Where like travel?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Have traveled abroad?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What favorite food?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Are you vegan?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Are you vegetarian?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Do you exercise?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What favorite movie?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What favorite book?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What favorite music?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Do you like sports?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Are you religious?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What is religion?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What political views?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What favorite color?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What zodiac sign?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Introvert or extrovert?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What makes happy?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What biggest fear?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What do regret?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Where were born?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What hometown?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Where currently live?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What country from?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What culture from?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What is age?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'How old are?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'When birthday?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What childhood like?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What inspired you?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Who inspired you?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Where work currently?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What job title?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Working full-time?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Are self-employed?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Looking for work?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What salary?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'How much earn?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What net worth?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Do have debt?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'How much debt?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'How mental health?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Do see therapist?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Do take medication?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Do have anxiety?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Do have depression?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Are you happy?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Do you meditate?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Do you yoga?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'How often exercise?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Are fit?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What weight?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What height?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Do sleep well?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Do have Instagram?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Are on social media?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'How often social?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Do use Facebook?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Do use Twitter?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Do like gaming?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What games play?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What phone model?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Mac or Windows?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What favorite site?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What humor?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What favorite sport?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What personality type?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What is dream?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What goal life?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Where see in 10 years?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Do believe fate?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Do believe luck?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What life philosophy?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Does she boyfriend?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Does she girlfriend?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'When break up?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Does want marry?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Does want kids?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Do live family?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Do have roommates?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Who best friend?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'How many close friends?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What partner do?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'When meet partner?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Do have pet?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'How spend weekends?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Do go out often?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What favorite country?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Are morning person?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'When do sleep?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What diet?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Do cook?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Do wear glasses?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What clothing style?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Do like fashion?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What aesthetic?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What favorite number?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Are introverted?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Are extroverted?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Are ambivert?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What makes sad?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What biggest achievement?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What school go to?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Remember first job?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What first career?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Have role models?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Who is role model?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What biggest influence?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What turning point?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Have challenges?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What biggest challenge?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'How overcome it?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What shaped you?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What company work?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Working part-time?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Are freelancing?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Are unemployed?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Job hunting?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'How many jobs?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Like your job?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Enjoy your work?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Satisfied at work?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Want change careers?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Considering job offers?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Have received offers?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'How much make?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'How much saved?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'In therapy?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Have health issues?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'How many sleep hours?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Have medical conditions?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What Instagram handle?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'How many followers?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Post personal life?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Use TikTok?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Favorite social media?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Video call often?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'How often text?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Like emojis?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Apple or Android?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What computer use?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Does she have parents?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What parents names?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Does she siblings?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What she studying?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Where she living?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'How is she?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Is she well?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What she like do?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What favorite thing?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Does have hobbies?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Does like movies?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What movies like?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Does have car?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Can she drive?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Does travel?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Where traveled?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What place?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Drink coffee?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Use Instagram?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What Instagram?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What her Instagram?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Does she smoke?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Does she drink?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What her routine?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'How she spending time?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Where she hang out?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Who her friends?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What she thinking?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'How she feeling today?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What her mood?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Is she stressed?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Is she tired?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Does she get sick?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What her health like?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Does she have allergies?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What medications she take?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Does she take vitamins?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'How tall is she?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What she weigh?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What her body type?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Does she workout?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What her fitness routine?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Does she run?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Does she do cardio?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What her favorite exercise?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Does she lift weights?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Is she strong?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Can she do pushups?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What her mile time?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Does she play sports?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What sports she play?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Is she athletic?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Was she athlete?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Did she play in school?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What teams was she on?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Did she win awards?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What her biggest win?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What her record?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'How competitive is she?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Does she like winning?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'How handle losing?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What her weakness?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What her strength?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What bad at?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What good at?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Can she sing?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Can she dance?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Can she play instrument?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What instrument?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Does she like music?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What music she listen?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Who favorite artist?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Been to concerts?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What last concert?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Does she festival?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What festivals been to?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Does she travel much?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Where been?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What favorite place?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Where want go?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What on bucket list?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Has she been Europe?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Has she been Asia?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Where in US?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Does she like beach?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Or mountains?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'City or country?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Where dream vacation?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What about family trips?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Travel with friends?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Solo travel?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'How she get around?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Does she drive?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What car she have?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Does she own car?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Does she take public transit?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Does she bike?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Does she walk?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'How commute?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What her commute like?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'How long commute?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Does she like job?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What she do after work?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What weeknight routine?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What weekend routine?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What Saturday like?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What Sunday like?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'How spend free time?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What do alone?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What do with others?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Does she go bars?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Does she drink alcohol?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'How much drink?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Does she party?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'How often go out?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What nightlife like?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Does she date?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'How dating life?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'On dating apps?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What apps use?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Looking for relationship?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What type person?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What her type?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What she attracted to?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What turn offs?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Deal breakers?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Past relationships?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'How many exes?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Still talk exes?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Good terms?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What went wrong?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Why breakup?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Was it mutual?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Who broke up?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'How long relationship?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'When last relationship?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Currently dating?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Seeing someone?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'In love?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What her love life?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Happy in relationship?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What partner like?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'How they meet?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'How long together?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Living together?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Thinking marriage?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Want get married?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'Want have kids?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'How many kids want?', expectType: 'personal', shouldDeferToEmail: true },
  { q: 'What parenting style?', expectType: 'personal', shouldDeferToEmail: true },
];

const context = { projectsDiscussed: [], askedAboutContact: false, askedAboutSkills: false };

console.log('='.repeat(80));
console.log('AI CHAT RESPONSE ACCURACY TEST');
console.log('='.repeat(80));
console.log('');

let correct = 0;
let incorrect = 0;
const issues: any[] = [];

for (const test of testCases) {
  const result = generateSmartResponse(test.q, context);
  const hasEmailSuggestion = result.suggestions.includes('Email Karishma');
  const hasDeferralResponse = result.response.includes('ask her personally') || 
                              result.response.includes('might have to ask her');
  
  const isCorrect = test.shouldDeferToEmail 
    ? (hasEmailSuggestion && hasDeferralResponse)
    : (!hasEmailSuggestion && !hasDeferralResponse);
  
  if (isCorrect) {
    correct++;
    console.log('✅ CORRECT');
  } else {
    incorrect++;
    console.log('❌ INCORRECT');
    issues.push({
      question: test.q,
      expected: test.expectType,
      shouldDefer: test.shouldDeferToEmail,
      actualDefer: hasEmailSuggestion
    });
  }
  
  console.log('Q:', test.q);
  console.log('Expected Type:', test.expectType);
  console.log('Should Defer:', test.shouldDeferToEmail ? 'YES' : 'NO');
  console.log('Response:', result.response.substring(0, 200) + '...');
  console.log('Suggestions:', result.suggestions.join(' | '));
  console.log('');
}

console.log('='.repeat(80));
console.log(`RESULTS: ${correct} correct, ${incorrect} incorrect out of ${testCases.length} tests`);
console.log('='.repeat(80));

if (issues.length > 0) {
  console.log('');
  console.log('ISSUES FOUND:');
  console.log('-------------');
  issues.forEach(issue => {
    console.log(`\nQuestion: ${issue.question}`);
    console.log(`Expected: ${issue.expected} (Defer: ${issue.shouldDefer})`);
    console.log(`Got: Defer = ${issue.actualDefer}`);
  });
}
