// 500+ Private, Ambiguous, and Unanswerable Questions
// All should be answered with "ask her personally" + email

export const privateQuestions = [
  // Personal & Family (1-50)
  "What is her father's name?",
  "What is her mother's name?",
  "Does she have any siblings?",
  "How many brothers does she have?",
  "How many sisters does she have?",
  "Is she married?",
  "Does she have a boyfriend?",
  "Does she have a girlfriend?",
  "Is she single?",
  "Does she have children?",
  "How old is she?",
  "When is her birthday?",
  "What is her age?",
  "Where was she born?",
  "Where did she grow up?",
  "What is her hometown?",
  "Where does she live now?",
  "What is her address?",
  "What is her phone number?",
  "Does she have pets?",
  "What pets does she have?",
  "Does she have a dog?",
  "Does she have a cat?",
  "What is her family background?",
  "Is her family supportive?",
  "What do her parents do?",
  "Where do her parents live?",
  "Is she close to her family?",
  "Does she have a partner?",
  "Who is she dating?",
  "Is she in a relationship?",
  "Is she engaged?",
  "What is her marital status?",
  "Does she want kids?",
  "How many kids does she want?",
  "What are her parents' names?",
  "What does her father do?",
  "What does her mother do?",
  "Is she an only child?",
  "Does she have step-siblings?",
  "What is her maiden name?",
  "Is she divorced?",
  "Has she been married before?",
  "What is her spouse's name?",
  "What does her partner do?",
  "Where does her family live?",
  "Is her family from Boston?",
  "What is her ethnic background?",
  "What is her nationality?",
  "Is she a citizen?",
  
  // Current Work & Status (51-100)
  "Where is she working currently?",
  "What is her current job?",
  "Where does she work?",
  "What project is she working on now?",
  "What is she working on right now?",
  "Is she employed?",
  "Who is her current employer?",
  "What company does she work for?",
  "Is she freelancing now?",
  "What is her current position?",
  "What is her job title?",
  "Who does she work for?",
  "Is she still at Northeastern?",
  "Did she graduate?",
  "Is she working full-time?",
  "Is she working part-time?",
  "Is she a student?",
  "What is she studying now?",
  "Is she in school?",
  "What courses is she taking?",
  "Where is she studying?",
  "When will she graduate?",
  "Has she finished her degree?",
  "Is she looking for work?",
  "Is she available for work?",
  "Is she open to opportunities?",
  "What is her availability?",
  "When can she start?",
  "Is she interviewing?",
  "Has she found a job?",
  "Is she employed right now?",
  "What is her work schedule?",
  "Does she work remotely?",
  "Does she work in an office?",
  "Where is her office?",
  "What are her working hours?",
  "Does she work weekends?",
  "Is she busy?",
  "Is she available?",
  "What is she doing today?",
  "What is she doing this week?",
  "Is she on vacation?",
  "Is she traveling?",
  "Where is she right now?",
  "Is she in Boston?",
  "Has she moved?",
  "Where did she go?",
  "Is she out of town?",
  
  // Goals, Plans & Future (101-150)
  "What are her goals?",
  "What are her career goals?",
  "What are her life goals?",
  "What is her aim in life?",
  "What are her aspirations?",
  "What are her dreams?",
  "What are her ambitions?",
  "Where does she see herself in 5 years?",
  "Where does she see herself in 10 years?",
  "What are her future plans?",
  "What is she planning next?",
  "What's next for her?",
  "What are her next steps?",
  "What is her vision?",
  "What does she want to achieve?",
  "What is she aiming for?",
  "What are her objectives?",
  "What is her ultimate goal?",
  "Where does she want to be?",
  "What does she want to become?",
  "What is her dream job?",
  "Where does she want to work?",
  "What companies is she targeting?",
  "Is she looking for a new job?",
  "Does she want to start a business?",
  "Will she start her own company?",
  "Does she want to freelance?",
  "Is she planning to relocate?",
  "Will she move?",
  "Where does she want to live?",
  "Does she want to travel?",
  "What are her travel plans?",
  "Where does she want to go?",
  "Is she planning a trip?",
  "What is she saving for?",
  "What are her financial goals?",
  "Does she want to buy a house?",
  "Is she planning to buy property?",
  "What are her retirement plans?",
  "How long does she want to work?",
  "When will she retire?",
  "What is her five-year plan?",
  "What is her ten-year plan?",
  "What are her short-term goals?",
  "What are her long-term goals?",
  "What does success mean to her?",
  "How does she define success?",
  "What motivates her?",
  "What drives her?",
  "What inspires her?",
  
  // Opinions & Preferences (151-200)
  "What does she think about AI?",
  "What is her opinion on remote work?",
  "What does she prefer?",
  "What is her favorite color?",
  "What is her favorite food?",
  "What is her favorite movie?",
  "What is her favorite book?",
  "What is her favorite song?",
  "What is her favorite band?",
  "What is her favorite city?",
  "What is her favorite restaurant?",
  "What does she like to eat?",
  "What music does she listen to?",
  "What shows does she watch?",
  "What does she do for fun?",
  "What are her hobbies?",
  "What are her interests?",
  "What does she enjoy?",
  "What makes her happy?",
  "What makes her sad?",
  "What annoys her?",
  "What frustrates her?",
  "What does she hate?",
  "What does she love?",
  "What is she passionate about?",
  "What does she care about?",
  "What matters to her?",
  "What is important to her?",
  "What are her values?",
  "What does she believe in?",
  "What is her religion?",
  "Is she religious?",
  "What is her political view?",
  "Who did she vote for?",
  "What are her political beliefs?",
  "Is she liberal or conservative?",
  "What causes does she support?",
  "What charities does she donate to?",
  "Is she involved in activism?",
  "What social issues matter to her?",
  "What does she think about climate change?",
  "What does she think about education?",
  "What does she think about healthcare?",
  "What is her stance on technology?",
  "Does she prefer Mac or PC?",
  "Does she use iPhone or Android?",
  "What phone does she have?",
  "What laptop does she use?",
  "What tools does she prefer?",
  "What software does she like?",
  
  // Lifestyle & Habits (201-250)
  "What is her daily routine?",
  "What time does she wake up?",
  "What time does she sleep?",
  "How many hours does she sleep?",
  "Is she a morning person?",
  "Is she a night owl?",
  "What does she do in the morning?",
  "What does she do at night?",
  "What does she eat for breakfast?",
  "What does she eat for lunch?",
  "What does she eat for dinner?",
  "Does she cook?",
  "What does she like to cook?",
  "Does she exercise?",
  "What is her workout routine?",
  "Does she go to the gym?",
  "What gym does she go to?",
  "Does she do yoga?",
  "Does she run?",
  "Does she play sports?",
  "What sports does she play?",
  "Is she athletic?",
  "Is she fit?",
  "What is her diet?",
  "Is she vegetarian?",
  "Is she vegan?",
  "Does she eat meat?",
  "Does she drink coffee?",
  "Does she drink tea?",
  "Does she drink alcohol?",
  "Does she smoke?",
  "What are her habits?",
  "What does she do on weekends?",
  "How does she spend her free time?",
  "What does she do to relax?",
  "How does she unwind?",
  "What is her stress relief?",
  "How does she handle stress?",
  "What makes her relaxed?",
  "Does she meditate?",
  "Does she journal?",
  "Does she read?",
  "What does she read?",
  "How many books does she read?",
  "What is she reading now?",
  "Does she watch TV?",
  "What shows is she watching?",
  "Does she play games?",
  "What games does she play?",
  "Is she a gamer?",
  "Does she go out?",
  
  // Social & Relationships (251-300)
  "Who are her friends?",
  "Does she have many friends?",
  "Who is her best friend?",
  "Is she social?",
  "Is she introverted?",
  "Is she extroverted?",
  "Does she like parties?",
  "Does she go to events?",
  "What social activities does she do?",
  "Is she active on social media?",
  "What social media does she use?",
  "What is her Instagram?",
  "What is her Twitter?",
  "What is her LinkedIn?",
  "Can I follow her?",
  "Does she post often?",
  "What does she post about?",
  "Who does she follow?",
  "Who does she interact with?",
  "Is she popular?",
  "Does she have a mentor?",
  "Who is her mentor?",
  "Who does she look up to?",
  "Who inspires her?",
  "Who are her role models?",
  "Has she mentored anyone?",
  "Does she teach?",
  "Does she give advice?",
  "What advice would she give?",
  "What would she recommend?",
  "What does she suggest?",
  "How does she network?",
  "Where does she network?",
  "What communities is she in?",
  "What groups is she part of?",
  "Is she in any organizations?",
  "What clubs is she in?",
  "Does she volunteer?",
  "Where does she volunteer?",
  "What causes does she support?",
  "Is she charitable?",
  "Does she donate?",
  "How does she give back?",
  "Is she involved in her community?",
  "What does she do for others?",
  "Is she helpful?",
  "Is she kind?",
  "What is her personality?",
  "What is she like?",
  "How would you describe her?",
  "What are her strengths?",
  
  // Financial & Compensation (301-350)
  "What is her salary?",
  "How much does she earn?",
  "How much does she make?",
  "What is her income?",
  "What is her net worth?",
  "How much is she worth?",
  "How much does she charge?",
  "What are her rates?",
  "How expensive is she?",
  "Is she expensive?",
  "Can I afford her?",
  "What is her hourly rate?",
  "What is her day rate?",
  "What is her project rate?",
  "How much for a website?",
  "How much for a logo?",
  "How much for consulting?",
  "What is her retainer fee?",
  "Does she offer payment plans?",
  "Can I pay in installments?",
  "Does she accept crypto?",
  "What payment methods does she accept?",
  "Does she negotiate?",
  "Can I get a discount?",
  "Does she offer student discounts?",
  "Does she offer non-profit discounts?",
  "Is she negotiable on price?",
  "What is her budget range?",
  "What is her minimum project size?",
  "Does she do small projects?",
  "Does she do large projects?",
  "How much for a quick consultation?",
  "Does she charge for discovery?",
  "Is discovery free?",
  "Does she do free work?",
  "Will she work for equity?",
  "Will she work for exposure?",
  "Does she do pro bono work?",
  "Can she work within my budget?",
  "What if I can't afford her?",
  "Does she have a waiting list?",
  "How booked is she?",
  "When is she available?",
  "Can she start tomorrow?",
  "Can she start next week?",
  "How soon can she start?",
  "Is she taking new clients?",
  "Is she accepting projects?",
  "Does she have capacity?",
  "Is she too busy?",
  
  // Health & Medical (351-380)
  "Is she healthy?",
  "Does she have health issues?",
  "What medical conditions does she have?",
  "Is she sick?",
  "Has she been sick?",
  "Does she take medication?",
  "What medication does she take?",
  "Does she have allergies?",
  "What is she allergic to?",
  "Does she wear glasses?",
  "Does she wear contacts?",
  "What is her height?",
  "What is her weight?",
  "What is her body type?",
  "Does she have disabilities?",
  "Does she have any conditions?",
  "Has she had surgery?",
  "Has she been hospitalized?",
  "Does she see a doctor?",
  "Does she see a therapist?",
  "Does she have mental health issues?",
  "Is she depressed?",
  "Does she have anxiety?",
  "Is she stressed?",
  "How is her mental health?",
  "How is her physical health?",
  "Is she in good shape?",
  "Does she take vitamins?",
  "What supplements does she take?",
  "Does she have insurance?",
  
  // Education & Background (381-420)
  "Where did she go to school?",
  "What high school did she attend?",
  "What college did she go to?",
  "Where did she get her bachelor's?",
  "What was her undergraduate major?",
  "What did she study in undergrad?",
  "Did she go to graduate school?",
  "What graduate school did she attend?",
  "What is her GPA?",
  "Did she get good grades?",
  "Was she a good student?",
  "Did she graduate with honors?",
  "What year did she graduate?",
  "When did she finish school?",
  "Did she take a gap year?",
  "Did she study abroad?",
  "Where did she study abroad?",
  "What scholarships did she get?",
  "Did she have student loans?",
  "How much student debt does she have?",
  "Did she pay off her loans?",
  "Was she in a sorority?",
  "Was she in a fraternity?",
  "What clubs was she in?",
  "What activities did she do?",
  "Was she athletic in school?",
  "What sports did she play?",
  "Did she have a job in college?",
  "How did she pay for college?",
  "Did her parents pay?",
  "Did she work during school?",
  "What was her first job?",
  "When did she start working?",
  "What internships did she have?",
  "Where did she intern?",
  "Who did she intern for?",
  "What was her thesis about?",
  "Did she do research?",
  "What did she research?",
  
  // Hypothetical & Unanswerable (421-470)
  "Will she work with me?",
  "Would she be interested?",
  "Can she help me?",
  "Should I hire her?",
  "Is she the right fit?",
  "Will she like my project?",
  "Would she enjoy this work?",
  "Can she do this?",
  "Is she capable of this?",
  "Has she done this before?",
  "Would she be good at this?",
  "Can she handle this?",
  "Is this within her scope?",
  "Would she recommend?",
  "What would she do?",
  "How would she approach this?",
  "What would she suggest?",
  "If she were me, what would she do?",
  "What if I can't pay?",
  "What if my project fails?",
  "What if I don't like it?",
  "What if we disagree?",
  "What happens if?",
  "Can she guarantee results?",
  "Will this work?",
  "Will this succeed?",
  "Is this a good idea?",
  "Should I do this?",
  "What do you think I should do?",
  "Can you give me advice?",
  "What would Karishma say?",
  "How would she feel about?",
  "Would she approve?",
  "Does she agree with?",
  "What is her take on?",
  "How does she feel about?",
  "Is she happy with?",
  "Is she satisfied with?",
  "Does she regret?",
  "What are her regrets?",
  "What mistakes has she made?",
  "What has she learned?",
  "What would she change?",
  "What would she do differently?",
  "If she could go back?",
  "What is her biggest failure?",
  "What is her biggest success?",
  "What is she most proud of?",
  "What is her proudest moment?",
  "What is her greatest achievement?",
  
  // Random Personal (471-500)
  "What car does she drive?",
  "Does she own a car?",
  "Does she have a driver's license?",
  "Can she drive?",
  "Does she take public transportation?",
  "How does she commute?",
  "Where does she park?",
  "What is her commute like?",
  "How long is her commute?",
  "Does she work from home?",
  "Does she have a home office?",
  "What does her workspace look like?",
  "What is her setup?",
  "What desk does she have?",
  "What chair does she use?",
  "What monitor does she have?",
  "What keyboard does she use?",
  "What mouse does she use?",
  "Does she use a standing desk?",
  "What decorations does she have?",
  "What is on her walls?",
  "What plants does she have?",
  "Does she like plants?",
  "What does her apartment look like?",
  "How big is her place?",
  "Does she rent or own?",
  "How much is her rent?",
  "Does she have roommates?",
  "Who does she live with?",
  "Does she live alone?",
]
